### ISSUE TITLE
The script class can't be abstract

### ISSUE THREAD

**Issue by CuteWaterBeary** [ReinaS-64892/TexTransTool#111]
The second line of 
```csharp
[AddComponentMenu("TexTransTool/AvatarDomainDefinition")]
[RequireComponent(typeof(AbstractTexTransGroup))]
```
 found on `AvatarDomainDefinition.cs` causes this error:

<img width="287" alt="2023-08-30-16-39-44" src="https://github.com/ReinaS-64892/TexTransTool/assets/103973703/88a98438-631b-484d-a3a1-d590f401f46f">

**Comment by CuteWaterBeary** [comment]
This happens when I try to add the component to any GameObject

**Comment by ReinaS-64892** [comment]
You must first add a "TexTransGroup" or "TexTransParentGroup" that inherits from "AbstractTexTransGroup" to the GameObject.

I have added this to the English lead me, but I don't understand English very well, so please review.

**Comment by ReinaS-64892** [comment]
@CuteWaterBeary
I have added this to the English readme, but I don't understand English very well, so please review.

**Comment by CuteWaterBeary** [comment]
> rst add a "TexTransGr

Just read it - it's good.

**Comment by CuteWaterBeary** [comment]
> You must first add a "TexTransGroup" or "TexTransParentGroup" that inherits from "AbstractTexTransGroup" to the GameObject.

Thank you - that solved it.
