### ISSUE TITLE
GUID Duplicate

### ISSUE THREAD

**Issue by anatawa12** [ReinaS-64892/TexTransTool#136]
https://github.com/ReinaS-64892/TexTransTool/blob/10a1c97e134b7ccdb6191fed79ddd627a9a506ef/Editor/Inspector/TextureAtlas.meta#L2
https://github.com/ReinaS-64892/TexTransTool/blob/10a1c97e134b7ccdb6191fed79ddd627a9a506ef/Editor/TextureAtlas.meta#L2

**Comment by ReinaS-64892** [comment]
先ほど修正入れました～ https://github.com/ReinaS-64892/TexTransTool/commit/71968e19957b6aa5ede398677c949b7911f310a3

**Comment by anatawa12** [comment]
よさそう~
