### ISSUE TITLE
AtrasTextureにおいて結合後UVに誤差がある

### ISSUE THREAD

**Issue by Narazaka** [ReinaS-64892/TexTransTool#296]
特に小さな領域をアトラスに指定する場合、座標変換誤差のようなものが見受けられます（単に滲むでは無く平行移動のように見える場合があるため）。
これは技術的により元に忠実なように出来たりするものでしょうか？（多少の変化を気にしなければ使えないこともないと思いますが）

元
![image](https://github.com/ReinaS-64892/TexTransTool/assets/1712548/645461d1-36e0-491e-9805-1f2bfb69eca7)
アトラスプレビュー（テクスチャの地部分が干渉して縁が黒くなっている）
![image](https://github.com/ReinaS-64892/TexTransTool/assets/1712548/5b1eb90c-fc43-490c-aacd-02ab533bf76d)

元
![image](https://github.com/ReinaS-64892/TexTransTool/assets/1712548/c2bd6b52-3abc-439a-8f9b-1d115fc2b19c)
アトラステクスチャーサイズを2048にしたプレビュー（模様全体が若干下側にずれたように見える）
![image](https://github.com/ReinaS-64892/TexTransTool/assets/1712548/f5149e8b-4f4d-4c3c-8810-41210edbe4f0)
アトラステクスチャーサイズを512にしたプレビュー（加えてTransparentなテスクチャがモデル内方に寄って小さくなったように見える）
![image](https://github.com/ReinaS-64892/TexTransTool/assets/1712548/ab18de66-6761-4292-a780-e1a06e0328fc)

**Comment by ReinaS-64892** [comment]
使っているバージョンは v0.4.4 ですか？ #280 で修正したバグと同じであれば [v0.5.0-Beta.6](https://github.com/ReinaS-64892/TexTransTool/releases/tag/v0.5.0-Beta.6) 以降であれば修正されているはずなので確認してみてほしいです！

ただ、もし Unity2019の環境で v0.5.0-Beta.x を入れれない場合であれば パディングを0にすることで回避できると思います。

**Comment by Narazaka** [comment]
0.4.4です。なるほど2019なので0.5系試せないですが、パディング試してみます。

**Comment by Narazaka** [comment]
パディング0であればたしかにズレはほぼ無いように感じました
