### ISSUE TITLE
TTT Atras Textureで初期状態でinactiveなオブジェクトもアトラス化したい

### ISSUE THREAD

**Issue by Narazaka** [ReinaS-64892/TexTransTool#297]
SafetyによりAnimatorが動作しない状態でも正しく初期状態を表示するため、あえてGameObjectを初期inactiveでアップロードする場合がありますが、TTT Atras TextureがactiveなGameObjectしか扱わないためこの運用が不可能になっています。

0.4.4なので0.5系で直っているなら閉じていただいて構いません。

**Comment by ReinaS-64892** [comment]
[AAO](https://github.com/anatawa12/AvatarOptimizer) で 状況によりますが inactive なメッシュが削除されることもあり、inactiveなメッシュは基本的にはアトラス化対象に含まないのが仕様です。
ですが、そのような場合も想定はしていて、#222 にて IncludeDisableRenderer が v0.5.0-Bata.xで使用可能です。

**Comment by Narazaka** [comment]
どちらかといえばIncludeDisableRenderer的な挙動をデフォルト挙動にした方が望ましいのではと思いますがいかがでしょうか。

- AAOに削除されるメッシュは存在しうるとはいえ、そのようなメッシュはアップロード者自身も認識しているはずであり、必ず手動設定が必要となるTTT Atras Textureにおいて不要にチェックされる可能性は少ないのではないかと思います。
- TTT Atras Textureを設定後にメッシュをinactiveにした場合アトラス化が走らずに重たいメッシュが含まれる可能性があります。
  - 意図せず不要な部分までアトラス化される可能性と、アトラス化が意図せずはずれる可能性について、どちらがクリティカルで可能性が高いかは判断が難しいですが……
- IncludeDisableRenderer（無効なレンダラーを含める）の意味が取りづらく、理解されずに応急的にメッシュをactiveにしてfallback時に誤表示する状態になったり、あるいは利用を諦められてしまう危険性があると思います。
  - 名称によって分かりやすくなる可能性はある

**Comment by ReinaS-64892** [comment]
このあたりの仕様はAtlasTextureの設計思想に抵触するあたりであり長めな前置きを置きます。
まず、アトラス化する意味はいくつかあると私は認識していて

- マテリアルのマージが主目的
テクスチャを一つにすることによりマテリアルのマージができるようになり、それによってSetPassCallなどを減らせること

- VRAM削減が主目的
テクスチャの必要な部分だけ集めた一つのテクスチャにすることで、VRAMの不必要な消費を抑えること

それで、AtlasTextureは私が欲しいから作った代物で、後者に寄った設定がデフォルトで、基本的にVRAMの削減をメインの機能としており、あくまで、マテリアルがマージできるのはQuest対応などのエッジケースや、すべてを理解している人向けです。
私は複数衣装を入れない人なので正しくないかもしれないですが、複数衣装環境でのアトラス化の意味というのは 、マテリアルのマージが主目的...というよりはRuntimeの状況に応じて変わる負荷を抑えるためというのを感じます。
逆に状況に応じて変わることのないVRAM容量は削減というのは、アニメーションでメッシュの可視設定が操作される複数衣装などの環境では、まずするべきVRAM削減は1アバター1衣装にすることであり、AtlasTextureがデフォルトで対応するべき環境ではないということ。

**Comment by ReinaS-64892** [comment]
ここからがそれぞれの回答になりますが、

>- AAOに削除されるメッシュは存在しうるとはいえ、そのようなメッシュはアップロード者自身も認識しているはずであり、必ず手動設定が必要となるTTT Atras Textureにおいて不要にチェックされる可能性は少ないのではないかと思います。

それは、[AAO](https://github.com/anatawa12/AvatarOptimizer)の T&O に任せて無効化するだけで削除されることを期待する環境では手動でアトラス化対象に入れるよう設定すること要求するということであっているでしょうか？
私はそれを期待していることが多く、それに設定を求める方をデフォルトにするのは面倒くさいと思っているためそれをしたくありません。
あと...こちらがメインですが、設定時点で表示されているメッシュのみを対象とする、設定時点で表示されている物のみをアップロードする前提をデフォルトでは考えています。


>TTT Atras Textureを設定後にメッシュをinactiveにした場合アトラス化が走らずに重たいメッシュが含まれる可能性があります。
>  - 意図せず不要な部分までアトラス化される可能性と、アトラス化が意図せずはずれる可能性について、どちらがクリティカルで可能性が高いかは判断が難しいですが……

意図せず不要な部分のアトラス化が入ることはVRAMの不必要な浪費を招き、数値的にわかりずらく、一番恐れるべき事態で、
逆にアトラス化が意図せずはずれる可能性は、アップロードしてVRAMが著しく増加するため、アバターデータリストを見ればすぐにわかることで、前者のほうが避けるべき問題だと思っています。


>IncludeDisableRenderer（無効なレンダラーを含める）の意味が取りづらく、理解されずに応急的にメッシュをactiveにしてfallback時に誤表示する状態になったり、あるいは利用を諦められてしまう危険性があると思います。
>  - 名称によって分かりやすくなる可能性はある

そのような環境はまずデフォルトで対応すべき環境ではないということに尽きますが、
オプションで対応すべき環境ではあると思っているので、そのオプションの名前のわかりやすさは重要だと私も思っていて、言語選択が日本語の場合は特にその重要性は大きいので検討してみます。

**Comment by Narazaka** [comment]
ありがとうございます。

> まずするべきVRAM削減は1アバター1衣装にすること

私もいわゆる単一衣装派なので複数衣装前提の議論ではないつもりでした。ただしそのうえで単一衣装の場合においても服の部分着脱等アニメーションでメッシュの可視設定が操作されることが想定され、メッシュ干渉対策のためにデフォルトではinactiveにしておくべきメッシュが生じることがあります。

それはさておき、

> 意図せず不要な部分のアトラス化が入ることはVRAMの不必要な浪費を招き、数値的にわかりずらく、一番恐れるべき事態で、
> 逆にアトラス化が意図せずはずれる可能性は、アップロードしてVRAMが著しく増加するため、アバターデータリストを見ればすぐにわかることで、前者のほうが避けるべき問題だと思っています。

この説明に合点がいきましたので現状ママがベターだということ了解いたしました。

（先行最適化ではなくAAOのメッシュ削除と蜜に連携できるような道があれば理想的ですが、現状では難しそう……。）
