### ISSUE TITLE
ColorBurn Preview incorrect color

### ISSUE THREAD

**Issue by ReinaS-64892** [ReinaS-64892/TexTransTool#34]
#26 で実装したブレンドモードのプレビューでリニア色空間とガンマ色空間を変換して計算した場合でも
ほかはほぼ同じなのに対し、焼きこみカラー(ColorBurn)だけ適応したときと違う色合いになってしまっている。

**Comment by SASIKI-64892** [comment]
ただテストケースが悪かったらしく正常に表示されるケースもある模様なので謎ですね。
