### ISSUE TITLE
TTT MultiLayerImageCanvasに複数TargetRendererを指定したい

### ISSUE THREAD

**Issue by bdunderscore** [ReinaS-64892/TexTransTool#340]
Hair + Kemono_ear + Kemono_tailみたいな、メッシュが分割されてるけど同じマテリアルを使っている場合に対応するためです。
AAOをかけて統合しても、処理順的にTTTのほうが先に来そう・・・

**Comment by ReinaS-64892** [comment]
それらの項目はテクスチャを間接的に指定するための設定で、複数メッシュに渡っていたとしても、同じテクスチャを参照していればすべてのレンダラーに効果がありますよ

TargetRenderer という名前はちょっと混乱を招くと思っているので、いずれ違う形で何とかします。

**Comment by ReinaS-64892** [comment]
#347 あたりで名称に調整をいれましたし、以前から同じテクスチャを参照していればすべてのレンダラーに影響するのでこのissue 解決とみてクローズしますね！
