### ISSUE TITLE
サフィーちゃんのHairFrontTransparentを単体でアトラスすると、Previewでぐちゃぐちゃになる

### ISSUE THREAD

**Issue by bdunderscore** [ReinaS-64892/TexTransTool#402]
![image](https://github.com/ReinaS-64892/TexTransTool/assets/64174065/6e3fdb2e-4c9f-4095-b35a-c17d3933e666)

**Comment by bdunderscore** [comment]
![image](https://github.com/ReinaS-64892/TexTransTool/assets/64174065/b526e123-0986-47ab-91af-e9751f61939f)

**Comment by ReinaS-64892** [comment]
サフィーちゃんの前髪に限っては Weld Vertices をオフにすることで一時的な回避ができるようですね
だけど...それも、ClothOutwear についてる名札のようなケースが壊れるのは回避できないみたいです。
