### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Spokeek** [ReinaS-64892/TexTransTool#404]
I know that's not the first feature you want to add, but tool is quite complex with multiple components and options.

I would be very grateful if we could have an English translation, maybe done with DeepL

Thank you again for such a great tool.

**Comment by Spokeek** [comment]
Any possibility to add a translation then ? I can't wrap my head on all the features of the tool because of that to be honest.

**Comment by ReinaS-64892** [comment]
I would like to create an English version of the AtlasTexture and SimpleDecal tutorials and references.
However...most of the other components are experimental, and some don't even have Japanese documentation. So please don't expect too much from that.

Japanese original text

AtlasTexture や SimpleDecal のチュートリアルとリファレンスに関しては英語版を作りたいとは考えています。
ただ...それ以外のコンポーネントのほとんどは実験的なものであり、日本語版のドキュメントすら存在しないものもあります。なのでそこにはあまり期待しないでほしい。

**Comment by Spokeek** [comment]
その通りだ。もし英語のレビューが必要なら、遠慮なく言ってほしい。もし、英語のレビューが必要であれば、遠慮なく言ってほしい。 そして、私は期待しない。これはまだコミュニティーの仕事であり、素晴らしいコミュニティーの仕事だ。本当にありがとう。

English Original Text
That's perfectly fair. I asked again as i didn't heard about it. If you need an English review of it, don't hesitate.
And no i won't have expectation, this is still community work and it's great community work. Thank you again for it.

**Comment by Spokeek** [comment]
I know translation is in progress, so closing this.
