### ISSUE TITLE
Decal アップロード時にデカルが歪む　条件不明

### ISSUE THREAD

**Issue by inkuxuan** [ReinaS-64892/TexTransTool#515]
EditorでTransform、ScaleやMaxDistanceをあわせたあと、Upload後に歪むことがあります
条件不明（もう一回アップロードすると治ることが多い）
![image](https://github.com/ReinaS-64892/TexTransTool/assets/19793388/813475eb-0371-418e-acec-5c61bc1d987b)

![VRChat_2024-06-29_22-25-51 680_3840x2160](https://github.com/ReinaS-64892/TexTransTool/assets/19793388/b3d839a2-914d-470e-b5db-f8f955a7d811)

**Comment by ReinaS-64892** [comment]
さすがに条件がわからないとなると...何ともできないですね...

AdvancedOption - Padding  の値をゼロにすれば回避できるかもしれない...くらいしか見当がつかないです。
![image](https://github.com/ReinaS-64892/TexTransTool/assets/99442371/dc975d31-4559-410a-a269-abbda4147ad2)

**Comment by inkuxuan** [comment]
Padding=0で解決したようですのでCloseします！
