### ISSUE TITLE
Identifier uniqueness violationが発生する

### ISSUE THREAD

**Issue by bdunderscore** [ReinaS-64892/TexTransTool#522]
```
Identifier uniqueness violation: 'Name:RootCanvas/Umi_Face.psd-Canvas/おめめ/01/レイヤー 4, Type:GameObject'. Multiple Objects with the same name/type are generated by this Importer. There is no guarantee that subsequent imports of this asset will properly re-link to these targets.
UnityEditor.EditorGUI/PopupCallbackInfo:SetEnumValueDelegate (object,string[],int)
```
以上のエラーがリリース前のテストアバターのpsdで発生しました。TTTのバージョンは0.8.0-beta.0です。

**Comment by ReinaS-64892** [comment]
それは同一階層に同名のレイヤーが存在するときに発生するものなのだけど...名前ずらしたところで、再リンクが保証できないのは変わらないから...回避したところでって感じなのよね
静かに壊れるよりかは、それを発生させておいて、同一階層同名のレイヤーを作らないでくれって感じでもある...

**Comment by bdunderscore** [comment]
テストをもらったアバターでレイヤー名を変えられないかと聞いたけど、多すぎて無理って言われたので、レイヤー名をかぶらないように自動的に変更するツールがあったらアセット作者が変えやすくなるかも？

**Comment by ReinaS-64892** [comment]
さしずめ PSD Formatter みたいな感じかな... #212 あたりとも合わせて作ってみてもいい気はする

**Comment by ReinaS-64892** [comment]
フォーマッターは今後何れやるとしても、このエラーの発生自体は直さない方針なのでこの Issues はクローズするね！
