### ISSUE TITLE
TexTransTool 0.6.xから0.7.xへのマイグレーションでテクスチャ優先度設定が正しく変換されない

### ISSUE THREAD

**Issue by Narazaka** [ReinaS-64892/TexTransTool#551]
MaterialFineTuningValueにはAdditionalTextureSizeOffSetの値がそのまま入るが、これが1より大きい場合インスペクタで開くと1に強制されてしまうため設定値が無視されてしまう

![image](https://github.com/user-attachments/assets/1255ec6d-5269-4eb0-a176-a6e034ef2222)
![image](https://github.com/user-attachments/assets/8b50b37f-6dd7-4de3-9b6d-2cc2e70d2010)

**Comment by ReinaS-64892** [comment]
そのあたり拡大を禁止する意義が強くあまり考えていなかったのですが、そのあたりの拡大を優先度に落とし込むのはあった方がいいですね！何とかしてみます！
