### ISSUE TITLE
SingleGradationDecalのRealTimePreviewを切ると Missing (material) の表示になります

### ISSUE THREAD

**Issue by bdunderscore** [ReinaS-64892/TexTransTool#554]
TTT 0.7.6で再現。RealTimePreviewを切るとこうなります。
![image](https://github.com/user-attachments/assets/9b5df18f-3f50-4d97-beea-293889ef6d54)

なお表示上の問題だけで、いったんInspectorを閉じて開きなおすと治ります。

**Comment by ReinaS-64892** [comment]
NDMF-Preview のあたりで発生しなくなるだろうけど AtlasTexture と同じようにちゃんとハンドリングすべきですね...普通に放置してたものなので何とかします
