### ISSUE TITLE
TTT AtrasTextureにおいてノーマルマップが想定外に粗くなる

### ISSUE THREAD

**Issue by Narazaka** [ReinaS-64892/TexTransTool#572]
2048x2048のテクスチャを解像度を落とさず必要部分のみ切り出す目的で、以下のようにTTT AtrasTextureを設定しました。
![image](https://github.com/user-attachments/assets/1100b8f6-1a93-4015-9b65-95ea9534c52d)

このときMainTextureは特に問題ないのですが、NormalMapがなぜか等倍解像度であるはずなのに以下のように有意に粗い感じに変化します。
これは目標解像度を4Kにしたりテクスチャー詳細設定を空にしたりしてもこれ以上の品質になりません。
この事象故にTTT AtrasTextureを使用できない場合があり困っています。（全ての場合にこれに当たるわけではありませんが、これがNormalが細かくない故に目立たないのか、あるいは条件によって事象が起きたり起きなかったりするのかは不明です）

（前後比較は画像を別タブで開いて見比べるのが分かりやすいです）

元:
![image](https://github.com/user-attachments/assets/f52b5d52-6da0-4717-a12c-15bc2dd30d8e)
TTT AtrasTextureのプレビュー:
![image](https://github.com/user-attachments/assets/512cd8a1-b7e7-469f-b8ac-b9b5264a7d94)

元のNormal Map
![image](https://github.com/user-attachments/assets/3bd8603b-8458-4d4e-acf1-a78bebaeb84b)

プレビュー中のMainTexture
![image](https://github.com/user-attachments/assets/47cf0ce9-2ed4-4411-8d53-19efae367597)
プレビュー中のNormalMap
![image](https://github.com/user-attachments/assets/d52270a1-bb3e-4f16-9c2e-5acadfa8bd8a)
![image](https://github.com/user-attachments/assets/b5d17f35-b4e4-425f-afe7-c315263b2997)

**Comment by ReinaS-64892** [comment]
正直なところ何とも言えないですが、ピクセルノーマライズを有効にした場合に画質の変化がどうなるかが気になります。

**Comment by Narazaka** [comment]
ピクセルノーマライズ有効で同様の設定にしたところかなり改善されました（心なしか平行移動する雰囲気くらいなので元品質といって良さそう？）
![image](https://github.com/user-attachments/assets/1396c55a-21ed-483c-a713-f4a914bc175b)

**Comment by ReinaS-64892** [comment]
良さそうですね！であればこの issues は解決したとしてクローズしますね！
それはそうとして ピクセルノーマライズのスタビライズも考えておきます！
