### ISSUE TITLE
SimpleDecal won't work when target renderer's material has be animated

### ISSUE THREAD

**Issue by yelandiealma** [ReinaS-64892/TexTransTool#594]
I use SimpleDecal for my hair color, I found that as long as the original material is keyframed in the animation, SimpleDecal won't working.
I'm not sure if this is normal behavior or a bug.......

TTT 0.8.0-beta.4
NDMF 1.5.0-beta.1

**Comment by ReinaS-64892** [comment]
That's normal behavior. TexTransTool doesn't touch animations.

Touching animations means confronting Unity's biggest black box, which I don't want to do, so TTT doesn't touch anything related to Unity's animations.

So it's normal for SimpleDecals and other components to be destroyed by animations.

I forgot to write this in the documentation. I'll write it later! (The EN documentation will probably take a while...)

Thanks for reporting it!

<details>

<summary>Original Japanese text</summary>

それは通常の挙動です。TexTransTool はアニメーションを触りません。

アニメーションに触るということは Unity の一番大きなブラックボックスと対峙することになるため私がやりたくないので、TTT は Unity の Animation 関連には一切関与しません。

なので SimpleDecalやほかコンポーネントはアニメーションにより破壊されることが通常の挙動です。

これはドキュメントに書き忘れていたことでもあります。後で書いておきます！(ENドキュメントはかなり時間かかりそうですが...)

ご報告に感謝します！

</details>
