### ISSUE TITLE
プラグインにArgumentOutOfRangeExceptionのエラーが発生しました

### ISSUE THREAD

**Issue by mitsukimachikawa** [ReinaS-64892/TexTransTool#650]
初心者なので、使い方に間違いがあった可能性も高いです。
[https://note.com/sonoty_hearts/n/na535f660dadf](url)
を参考にしてマテリアルスロットを減らそうと、previewで見た目に問題がないことを確認するところまで行いました。
その後、プレイモードに入ると
![スクリーンショット 2024-09-14 193613](https://github.com/user-attachments/assets/d600d07d-5fe9-43af-be4b-a6aa3aff22ec)
の表示が出て、プラグイン作者にご報告くださいとの表記があったので報告させていただきます。
![スクリーンショット 2024-09-14 192748コピー](https://github.com/user-attachments/assets/fa8bbda0-fa60-413b-ac73-9f38f6e4d619)

**Comment by ReinaS-64892** [comment]
ご報告に感謝します！

エラーの内容的に、 AtlasTexture が マテリアルからテクスチャなどの情報を取得する部分で失敗しているようですね...
ただ...プレビューの場合にエラーが発生しないということは、何か他の非破壊ツールなどによって lilToon 派生の特別なシェーダーになっているなど可能性があります。

原因を調べるためには、そのアバターがどのようなシェーダーを使用しているのか、またほか非破壊ツールの使用状況などの情報が必要です！
あと、念のためですが Unity, NDMF, TexTransTool, のバージョン情報も教えていただけると嬉しいです！

**Comment by mitsukimachikawa** [comment]
ありがとうございます！
すみません、何分初めての改変なので勝手がわからず……
![スクリーンショット 2024-09-14 205439コピー](https://github.com/user-attachments/assets/a57126fe-c564-485f-a4ba-1036353b884a)
![スクリーンショット 2024-09-14 205713](https://github.com/user-attachments/assets/f134f071-d941-4f96-ab6b-4eaac8405dd7)
ツールの使用状況はこれで確認できるのでしょうか？何か不備があれば教えてください。
シェーダーですが、
![スクリーンショット 2024-09-14 212857](https://github.com/user-attachments/assets/99c09262-6de6-476a-82f3-beae31fe53a1)
でチェックをつけていないもの含めて18個のマテリアルがTargetになっている状態で上記のエラーが出たので、18個のマテリアルのシェーダーを確認しました。
確認したところ、
![スクリーンショット 2024-09-14 215810](https://github.com/user-attachments/assets/2cacb382-fa74-47ea-a129-e51ed302c4b5)
になっていました。
明らかに毛色の違いそうな⑮mitsuami_fakeshadow_Kipfelのチェックを外し
![スクリーンショット 2024-09-14 220711](https://github.com/user-attachments/assets/47179e29-79f3-43d7-bd0c-dc8d960f31f3)
プレイモードに入ったところ、何を誤ったか全身がメタリックになってしまいましたが
![スクリーンショット 2024-09-14 220741](https://github.com/user-attachments/assets/0df26749-0d38-4c39-ae9c-b661a01190d5)報告したエラーは発生しませんでした。
また、⑮にチェックが入っている状態だとpreviewに入れていなかったことにも気が付きました。
繰り返しになりますが、本当に何もわからないのでおかしなところがあれば教えてください。対応ありがとうございます。

**Comment by ReinaS-64892** [comment]
丁寧な情報提供ありがとうございます！

lilToonの [optinal] 系 が誤って 通常の lilToon だと認識されているケースですね、 #520 にて修正されているので、 v0.8.0 のリリースを待つか、NDMFのバージョンに気を付けつつ v0.8.0-rc.8 を使用してください！

あと...メタリックになっているのは、 マテリアルを結合する場合、`マテリアル結合時の参照`を割り当てなかった場合適当なマテリアルを使用してマージしてしまうので...運悪くメタリックなマテリアルが選ばれてしまっているようですね。

適当なマテリアルを`マテリアル結合時の参照`に割り当てることで回避できますよ！
