### ISSUE TITLE
AtlasTextureでReference Copyと同時にCompressを設定する場合Targetを指定しないと効かない

### ISSUE THREAD

**Issue by kxn4t** [ReinaS-64892/TexTransTool#653]
AtlasTextureでReference Copyと同時にCompressを設定する場合、Targetに指定されているほうを指定しないと設定が効かないようです。

たとえば、このようにメインテクスチャを輪郭線のテクスチャにも割り当てたいとき、TargetにOutlineTexを指定しますが、CompressでもOutlineTexを指定しないと効かないです。
MainTextureとして諸々設定されたものをそのままOutlineTexに割り当てることをイメージして設定するのが自然だろうと思うので、直感に反する感じがします。
![image](https://github.com/user-attachments/assets/e05b79ff-fd27-4ae3-81fc-7c7a8a287364)

Targetの方を指定しないと効かないのをずっと仕様だと思っていたんですが、ひょっとしたら単なるバグの可能性もあるなと思ったので報告だけしておきます。

**Comment by kxn4t** [comment]
あーーー、これ上から順に適用されるのでコピー後はコピー前のを指定しても効かないってだけですね？
なんとなく腑に落ちましたが、同じテクスチャを使うことになるので効いてくれても良いような気はしました。

**Comment by ReinaS-64892** [comment]
ReferenceCopy でコピーされた側は基本的に設定をすべて元の物を継承するように考えていたので普通に何かのバグですね...

**Comment by ReinaS-64892** [comment]
あ！原因に見当がついたので何とかしときます

**Comment by kxn4t** [comment]
なるほど？？？よろしくお願いします！！！
