### ISSUE TITLE
ターゲットルート未指定時、とりあえずアバターのルートから参照するオプション

### ISSUE THREAD

**Issue by ni1chigo2115** [ReinaS-64892/TexTransTool#671]
ターゲットルートの親元を指定したTTT Atlasコンポネートを利用したプレハブを使っていましたが、エラーが出てしまいました。
ターゲットの親元の正式な名前を指定しないと、指定が解除されてしまうようです。
これだと他の衣装に切り替えたときに逐一指定が必要になるので、アバター親元から指定するオプションがあるとちょっと楽かなと思いました

**Comment by ReinaS-64892** [comment]
v0.8.0 にて ターゲットルート は削除されます！
基本的にそのアバター全体を処理する形で、ターゲットルートがあった場所は[マテリアル選択候補の制限](https://dev.ttt.rs64.net/docs/Reference/AtlasTexture/#%E3%83%9E%E3%83%86%E3%83%AA%E3%82%A2%E3%83%AB%E9%81%B8%E6%8A%9E%E5%80%99%E8%A3%9C%E3%81%AE%E5%88%B6%E9%99%90)の制限になります。

オプションになるわけではないですが... v0.8.0-rc.11 にて使用することができるので試してみてください！
