### ISSUE TITLE
TextureConfiguratorを複数つけられるようにしてほしい

### ISSUE THREAD

**Issue by eai04191** [ReinaS-64892/TexTransTool#705]
複数のテクスチャの設定を変えたいことがあるため

**Comment by ReinaS-64892** [comment]
TextureConfigurator などの TTT のコンポーネントは 一つの GameObject に一つまでですが、複数の GameObject にひとつづつ付与することで、複数のテクスチャ設定することが可能です。
試してみてください！

**Comment by eai04191** [comment]
現状それで使えることはわかっているのですが、例えば顔に顔のテクスチャと表情エフェクト用のテクスチャがついていて、それぞれの設定を変えたい場合は、同じGameObjectにつけられたほうが便利であるための提案です

![image](https://github.com/user-attachments/assets/dec598b6-93e8-40f3-a0a5-2e7f653ee1bc)

**Comment by eai04191** [comment]
ちょっと触ってみて、確かに都度GameObject増やしても全く問題ないなと思ったのでcloseします
