### ISSUE TITLE
AtlasTextureでlilToonのMatcap2ndが含まれない

### ISSUE THREAD

**Issue by kxn4t** [ReinaS-64892/TexTransTool#741]
AtlasTextureにてMatcap 1stがオフで2ndがオンのマテリアルでは2ndが対象に含まれないようです。
1stもオンにしてみると2ndも含まれるようになりました。

1stオフで2ndオンのマテリアルでも2ndが対象に含まれるとうれしいです。

**Comment by ReinaS-64892** [comment]
どっかで直した気がするけど治ってなかった ... ? 
確認しておきます！
